# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: 'Execute Reusables'

on:
  workflow_dispatch:
jobs:
  call-workflow-a:
    uses: ./.github/workflows/workflow_a.yml@main
  call-workflow-dotnet:
    uses: ./.github/workflows/dotnet.yml
  call-workflow-b:
    uses: ./.github/workflows/workflow_a.yml