name: Skip on ignored paths

on:
  pull_request:
    paths-ignore:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
      - '**appSettings*.json'
      - '**Dockerfile'

  push:
    branches: 
      - main
    paths-ignore:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
      - '**appSettings*.json'
      - '**Dockerfile'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No build required" '
