name: Spell Check
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

# test with no permissions
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token#defining-access-for-the-github_token-permissions
permissions: {}

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v7
        with: 
          incremental_files_only: false