name: Spell Check
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

# test with no permissions
permissions:
  contents: none

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v7
        with: 
          incremental_files_only: false